### ISSUE TITLE
Not found issue when I do refresh to the page.

### ISSUE THREAD

**Issue by mohammed5d5d5d5d8d8d8** [Sedemstickx/jquery-spa#2]
The issue is after I go to a router, and refresh the page, it gives me an error.
![image](https://github.com/Sedemstickx/jquery-spa/assets/100992568/ad1c6d9b-f331-40ca-b9d4-382ed17a0b51)
Thank you for the library.

**Comment by Sedemstickx** [comment]
Hello, 

Please since you’re using apache web server have you configured the .htaccess file to ensure all page loads/reloads visit the index page? To prevent that error you must ensure all normal browser routing visits the index page

Thank you also and I appreciate you using this library
